export enum ValidationErrorCodes {
    required = 'required',
    validateWhiteSpace = 'validateWhiteSpace',
    pattern = 'pattern',
    alreadyExists = 'alreadyExists',
    validateCodeInputRequirement = 'validateCodeInputRequirement',
    validateSuffixToBeginWithAlphabestOrNumbers = 'validateSuffixToBeginWithAlphabestOrNumbers',
    InvalidateDate = 'InvalidateDate',
    InvalidValue = 'InvalidValue',
    max = 'max',
    min = 'min',
    maxlength = 'maxlength',
    minlength = 'minlength',
    fileDescriptionEmpty = 'fileDescriptionEmpty',
    jdasRequiredFieldsEmpty = 'jdasRequiredFieldsEmpty',
    selectedValueNo = 'selectedValueNo',
    actionStatusOpen = 'actionStatusOpen',
    isActionCompleteDateInvalid = 'isActionCompleteDateInvalid',
    selectDropdown = 'selectDropdown'
  }